### ISSUE TITLE
書式保持機能

### ISSUE THREAD

**Issue by yosufuturu** [flexphere/holdon#3]
・機能追加要望
書式保持機能があると便利なので追加してください！

・背景
word等のオフィスソフトに対してコピー＆ペーストする際、
表などのフォーマットを崩さずに作業したいため

・機能
ペーストする際に書式情報を付与する/付与しないを選択できる機能が欲しいです。
書式の有無は頻繁に切り替える確率が高いので、1アクションで切り替えられると幸せになれます！

メイン画面に画像のようなトグルスイッチ？で切り替えられると分かりやすいです。
![image](https://user-images.githubusercontent.com/53241470/123190668-f0a16480-d4da-11eb-98ae-a10e45dcde4a.png)

**Comment by flexphere** [comment]
could resolved by #5
